### ISSUE TITLE
可否考虑直接合并IPList for China，感觉这样能更有效？

### ISSUE THREAD

**Issue by Daymond** [pluwen/China-Domain-Whitelist#10]
看简介，是用的IPIP.net的IP库，直接合并过来用会不会很有帮助？

[@17mon/china_ip_list](https://github.com/17mon/china_ip_list/blob/master/china_ip_list.txt)

**Comment by pluwen** [comment]
两个考虑
1、插件的判断依据是域名，不是IP
2、这个IP库行数有点多，效率不高

暂时不考虑合并
