### ISSUE TITLE
你好，可以把直播网站加上去嘛

### ISSUE THREAD

**Issue by GoogleGFW** [pluwen/China-Domain-Whitelist#3]
虎牙 斗鱼之类的大流量站，

资讯类，不涉及账号安全验证的走了代理倒也无所谓，

这种视频流的跑外面绕一圈稍微有些麻烦，

谢谢！

**Comment by pluwen** [comment]
抱歉，我自己没有使用这两家的服务。
你可以添加相关网址，并提交 pr，我会尽快处理。

**Comment by lan542662** [comment]
非常高频使用的站点，非常适合白名单，建议继续维护，大流量的，cdn 类，知名站点，视频类可能用到.

**Comment by pluwen** [comment]
主要是根据自己的使用情况添加，如果你有其它的网站，也可以在这里回复，或者直接发 pull request 给我
